params:
  epochs: 30
  batch_size : 32
  no_classes: 10
  loss_functions: sparse_categorical_crossentropy
  metric: accuracy
  optimizer:  SGD
  validation_datasize: 5000



artifacts:
  artifacts_dir:  artifacts
  model_dir:  model
  plot_dir: plots
  model_name: model.h5
  CHECKPOINT_DIR: checkpoints


logs:

  logs_dir: logs_dir
  general_logs: general_logs
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs

